drop table if exists booking cascade ;
drop table if exists event cascade ;
drop table if exists users cascade ;
create table booking (number_of_seats_booked integer, booking_id bigint generated by default as identity, event_id bigint, last_updated_time timestamp(6), time_booked timestamp(6), user_id bigint, primary key (booking_id));
create table event (capacity integer, version integer, end_time timestamp(6), id bigint generated by default as identity, start_time timestamp(6), event_name varchar(255), primary key (id));
create table users (id bigint generated by default as identity, email varchar(255), name varchar(255), phone_number varchar(255), primary key (id));
alter table if exists booking add constraint FKiy2tdi4vrw2mljj6rqwmd698q foreign key (event_id) references event;
alter table if exists booking add constraint FK7udbel7q86k041591kj6lfmvw foreign key (user_id) references users;
