-- USERS TABLE
create table public.users (
                              id bigint generated by default as identity,
                              name varchar(255),
                              email varchar(255),
                              phone_number varchar(255),
                              primary key (id)
);

-- EVENTS TABLE
create table public.event (
                              id bigint generated by default as identity,
                              event_name varchar(255),
                              capacity integer,
                              start_time timestamp(6),
                              end_time timestamp(6),
                              version integer,
                              primary key (id)
);

-- BOOKING TABLE
create table public.booking (
                                booking_id bigint generated by default as identity,
                                user_id bigint not null,
                                event_id bigint not null,
                                number_of_seats_booked integer,
                                time_booked timestamp(6),
                                last_updated_time timestamp(6),
                                primary key (booking_id)
);

-- FOREIGN KEYS
alter table public.booking
    add constraint fk_booking_user
        foreign key (user_id)
            references public.users (id);

alter table public.booking
    add constraint fk_booking_event
        foreign key (event_id)
            references public.event (id);